Revert "Intergrate django-db-comments into `create_tables` mgm. command"
This reverts commit b4dcf8983dc6bbf2c66ed8d76039847cbbebeda6 as a hotfix
for AB#44268. import_schemas --create-tables fails on an id column that
does not exist. I cannot reproduce this locally as I hit a different bug
earlier in the process:

django.core.exceptions.FieldError: Cannot resolve keyword 'sbiActiviteitNummer' into field...

Skipping this doesn't do much as many datasets have this issue. No idea
what's going wrong here.